services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./mysite:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["sh", "-c", "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"]


